### ISSUE TITLE
Plugin does not compile with Nutch 2.3.1

### ISSUE THREAD

**Issue by hostingnuggets** [jorgelbg/mimetype-filter#1]
I would like to use your plugin with my Nutch 2.3.1 installation but unfortunately the compilation (`ant runtime`) fails. Below is the detailed output:

```
compile:
     [echo] Compiling plugin: mimetype-filter
    [javac] Compiling 1 source file to /home/user/tmp/apache-nutch-2.3.1/build/mimetype-filter/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /home/user/tmp/apache-nutch-2.3.1/src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java:28: error: cannot find symbol
    [javac] import org.apache.nutch.crawl.CrawlDatum;
    [javac]                              ^
    [javac]   symbol:   class CrawlDatum
    [javac]   location: package org.apache.nutch.crawl
    [javac] /home/user/tmp/apache-nutch-2.3.1/src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java:29: error: cannot find symbol
    [javac] import org.apache.nutch.crawl.Inlinks;
    [javac]                              ^
    [javac]   symbol:   class Inlinks
    [javac]   location: package org.apache.nutch.crawl
    [javac] /home/user/tmp/apache-nutch-2.3.1/src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java:74: error: cannot find symbol
    [javac]       CrawlDatum datum, Inlinks inlinks) throws IndexingException {
    [javac]       ^
    [javac]   symbol:   class CrawlDatum
    [javac]   location: class MimeTypeIndexingFilter
    [javac] /home/user/tmp/apache-nutch-2.3.1/src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java:74: error: cannot find symbol
    [javac]       CrawlDatum datum, Inlinks inlinks) throws IndexingException {
    [javac]                         ^
    [javac]   symbol:   class Inlinks
    [javac]   location: class MimeTypeIndexingFilter
    [javac] /home/user/tmp/apache-nutch-2.3.1/src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java:55: error: MimeTypeIndexingFilter is not abstract and does not override abstract method filter(NutchDocument,String,WebPage) in IndexingFilter
    [javac] public class MimeTypeIndexingFilter implements IndexingFilter {
    [javac]        ^
    [javac] /home/user/tmp/apache-nutch-2.3.1/src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java:72: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] /home/user/tmp/apache-nutch-2.3.1/src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java:85: error: cannot find symbol
    [javac]       contentType = parse.getData().getMeta(Response.CONTENT_TYPE);
    [javac]                          ^
    [javac]   symbol:   method getData()
    [javac]   location: variable parse of type Parse
    [javac] Note: /home/user/tmp/apache-nutch-2.3.1/src/plugin/mimetype-filter/src/java/org/apache/nutch/indexer/filter/MimeTypeIndexingFilter.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 7 errors
    [javac] 1 warning

BUILD FAILED
/home/user/tmp/apache-nutch-2.3.1/build.xml:113: The following error occurred while executing this line:
/home/user/tmp/apache-nutch-2.3.1/src/plugin/build.xml:43: The following error occurred while executing this line:
/home/user/tmp/apache-nutch-2.3.1/src/plugin/build-plugin.xml:117: Compile failed; see the compiler error output for details.
```

**Comment by jorgelbg** [comment]
This plugin is (at the moment) only compatible with Nutch 1.x. Nutch 2.x includes a lot of changes that are not backward compatible with plugins written for the 1.x version.

**Comment by hostingnuggets** [comment]
Thanks for the fast answer. Do you have an idea when this plugin will be ported to Nutch 2.x?

**Comment by jorgelbg** [comment]
Will try to do it over the next weekend. Since I usually don't use the 2.x branch it will be nice to have someone else to test.

**Comment by hostingnuggets** [comment]
@jorgelbg that would be great and I would be happy to test and report back to you.
